---
# package is not in bullseye repo (yet)
- name: Custom deb package on debian11+
  apt:
    deb: "{{ deb_url }}"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version is version('11', '>=')

- name: Install autopostgresqlbackup
  apt:
    name: autopostgresqlbackup

- name: Crate backup dir "{{ autopgbkp_backup_dir }}"
  file:
    path: "{{ autopgbkp_backup_dir }}"
    state: directory
    mode: 0700
    owner: "{{ autopgbkp_user }}"

- name: Install template
  template:
    src: autopostgresqlbackup.j2
    dest: /etc/default/autopostgresqlbackup
    mode: 0644

- block:
    - name: Get user home
      getent:
        database: passwd
        key: "{{ autopgbkp_user }}"
        split: ":"

    - name: Deploy .pgpass if needed
      template:
        src: pgpass.j2
        dest: "{{ getent_passwd[autopgbkp_user][4] }}/.pgpass"
        owner: "{{ autopgbkp_user }}"
        mode: 0600
  when:
    - autopgbkp_pass | length > 0

- block:
    - name: Remove default cron
      file:
        path: /etc/cron.daily/autopostgresqlbackup
        state: absent

    - name: Set custom cron
      cron: "{{ autopgbkp_cron_def }}"
  when: autopgbkp_custom_cron
